### ISSUE TITLE
Change text in the Informant Screen

### ISSUE THREAD

**Issue by davekilroy** [AppertaFoundation/Diadem#116]
Colin has given the new text to Dave

**Comment by rappel1** [comment]
Changes: 
(1) Remove the "terms of use" on the DiADeM app login screen.
(2) Replace the current single page Declaration page of the app with 2 pages as per below.
(3) Use the term "Assessor" rather than "Interviewer" on the app
(4) Relationship of Informant - The pull down menu presently includes the fields: "next of kin, patient's close relative, care home staff.  Add the following two fields: "LPA registered with OPG" and "none of the above "
---------
---------

MATERIAL CONSTITUTING INFORMED CONSENT

I, as the Assessor, have explained to the patient:
What the DiADeM  test is for and why I will be taking the patient through the test today
That at the end of the test they may have a diagnosis of Moderately Advanced Dementia
What this may mean in terms of Care planning, help and support going forward
If the result is positive that it will be helpful to have this recorded on their their GP record
That data is not shared with any other parties and that all records of the assessment will be held solely and safely by the GP or clinician responsible for the patient’s long term care.

I have made the patient and carers aware of the Privacy Notice information that provides full details of disclosure of the patient’s personal information and the people they should contact if they have any concerns.

[YES/ NO ;
IF YES - THEN PROCEED TO THE “DECLARATION OF CONSENT” BELOW
IF NO - THEN  ASSESSOR CANNOT PROCEED]

------- 
 DECLARATION OF CONSENT

I, as the Assessor, have established informed consent from the patient in accordance with the Mental Capacity Act 2005:
For the patient to undergo the DiADeM assessment;
For the Assessor to collect the patient’s personal data for the DiADeM assessment; and
For the clinician responsible for long term care to hold the DiADeM assessment report which includes patient’s personal data on the patient’s record.

[YES/ NO ;
IF YES - THEN THE DIADEM ASSESSMENT MAY PROCEED
IF NO - THEN THE TEXT BELOW IS PRESENTED TO THE ASSESSOR]

I, as the Assessor, have established:

The patient does NOT have capacity, in accordance with the Mental Capacity Act 2005,  to provide  informed consent:
For the patient to undergo the DiADeM assessment;
For the Assessor to collect the patient’s personal data for the DiADeM assessment; and
For the clinician responsible for long term care to hold the DiADeM assessment report which includes patient’s personal data on the patient’s record.

It is in the patient’s best interest to undertake a DiADeM assessment, and to share the DiADeM assessment report, which includes patient’s  personal data, with the clinician responsible for the long term care of the patient.

[YES/ NO ;
IF YES - THEN THE DIADEM ASSESSMENT MAY PROCEED
IF NO - THEN THE DIADEM ASSESSMENT MAY NOT BE CONDUCTED BY THE ASSESSOR]
----

**Comment by davekilroy** [comment]
This issue seems to link to the following two issues:

#"[IG] Amend Declaration screen (including logic) to use "Material Constituting Informed Consent" 
#77 

#"[IG] Add a new screen after the Declaration screen (including logic) to use "Declaration of Consent"
#108
